import mongoose from '../database';

const schema = {
    tin: { type: mongoose.SchemaTypes.String, required: true },
    npi: { type: mongoose.SchemaTypes.String, required: true },
    facility_name: { type: mongoose.SchemaTypes.String, required: true },
    specialty: { type: mongoose.SchemaTypes.String, required: true },
    dollars_at_risk: { type: mongoose.SchemaTypes.Decimal128, required: true },
    scatterplot_x_axis: { type: mongoose.SchemaTypes.Decimal128, required: true },
    scatterplot_y_axis: { type: mongoose.SchemaTypes.Decimal128, required: true },
    risk_group_num: { type: mongoose.SchemaTypes.Number, required: true },
    risk_score: { type: mongoose.SchemaTypes.Decimal128, required: true },
    unusual_coding_outpatient_services_during_admissions_pct: { type: mongoose.SchemaTypes.Decimal128, required: true },
    unusual_coding_outpatient_services_during_admissions_peer_group_median: { type: mongoose.SchemaTypes.Decimal128, required: true },
    unusual_coding_outpatient_services_during_admissions_percentile: { type: mongoose.SchemaTypes.Decimal128, required: true },
    unusual_coding_outpatient_services_during_admissions_color: { type: mongoose.SchemaTypes.Number, required: true },
    unusual_coding_unusual_bill_classification_pct: { type: mongoose.SchemaTypes.Decimal128, required: true },
    unusual_coding_unusual_bill_classification_peer_group_median: { type: mongoose.SchemaTypes.Decimal128, required: true },
    unusual_coding_unusual_bill_classification_percentile: { type: mongoose.SchemaTypes.Decimal128, required: true },
    unusual_coding_unusual_bill_classification_color: { type: mongoose.SchemaTypes.Number, required: true },
    unusual_coding_unusual_bill_classification_top1_cd: { type: mongoose.SchemaTypes.String, required: true },
    unusual_coding_unusual_bill_classification_top1_desc: { type: mongoose.SchemaTypes.String, required: true },
    unusual_coding_unusual_bill_classification_top1_amt: { type: mongoose.SchemaTypes.Decimal128, required: true },
    unusual_coding_unusual_bill_classification_top1_lob: { type: mongoose.SchemaTypes.String, required: true },
    unusual_coding_unusual_bill_classification_top2_cd: { type: mongoose.SchemaTypes.String, required: true },
    unusual_coding_unusual_bill_classification_top2_desc: { type: mongoose.SchemaTypes.String, required: true },
    unusual_coding_unusual_bill_classification_top2_amt: { type: mongoose.SchemaTypes.Decimal128, required: true },
    unusual_coding_unusual_bill_classification_top2_lob: { type: mongoose.SchemaTypes.String, required: true },
    unusual_coding_unusual_revenue_paid_pct: { type: mongoose.SchemaTypes.Decimal128, required: true },
    unusual_coding_unusual_revenue_paid_peer_group_median: { type: mongoose.SchemaTypes.Decimal128, required: true },
    unusual_coding_unusual_revenue_paid_percentile: { type: mongoose.SchemaTypes.Decimal128, required: true },
    unusual_coding_unusual_revenue_paid_color: { type: mongoose.SchemaTypes.Number, required: true },
    unusual_coding_unusual_revenue_paid_top1_cd: { type: mongoose.SchemaTypes.String, required: true },
    unusual_coding_unusual_revenue_paid_top1_desc: { type: mongoose.SchemaTypes.String, required: true },
    unusual_coding_unusual_revenue_paid_top1_amt: { type: mongoose.SchemaTypes.Decimal128, required: true },
    unusual_coding_unusual_revenue_paid_top1_lob: { type: mongoose.SchemaTypes.String, required: true },
    unusual_coding_unusual_revenue_paid_top1_bill_cls_cd: { type: mongoose.SchemaTypes.String, required: true },
    unusual_coding_unusual_revenue_paid_top2_cd: { type: mongoose.SchemaTypes.String, required: true },
    unusual_coding_unusual_revenue_paid_top2_desc: { type: mongoose.SchemaTypes.String, required: true },
    unusual_coding_unusual_revenue_paid_top2_amt: { type: mongoose.SchemaTypes.Decimal128, required: true },
    unusual_coding_unusual_revenue_paid_top2_lob: { type: mongoose.SchemaTypes.String, required: true },
    unusual_coding_unusual_revenue_paid_top2_bill_cls_cd: { type: mongoose.SchemaTypes.String, required: true },
    unusual_coding_unusual_icd_procedure_paid_pct: { type: mongoose.SchemaTypes.Decimal128, required: true },
    unusual_coding_unusual_icd_procedure_paid_peer_group_median: { type: mongoose.SchemaTypes.Decimal128, required: true },
    unusual_coding_unusual_icd_procedure_paid_percentile: { type: mongoose.SchemaTypes.Decimal128, required: true },
    unusual_coding_unusual_icd_procedure_paid_color: { type: mongoose.SchemaTypes.Number, required: true },
    unusual_coding_unusual_icd_procedure_paid_top1_cd: { type: mongoose.SchemaTypes.String, required: true },
    unusual_coding_unusual_icd_procedure_paid_top1_desc: { type: mongoose.SchemaTypes.String, required: true },
    unusual_coding_unusual_icd_procedure_paid_top1_amt: { type: mongoose.SchemaTypes.Decimal128, required: true },
    unusual_coding_unusual_icd_procedure_paid_top1_lob: { type: mongoose.SchemaTypes.String, required: true },
    unusual_coding_unusual_icd_procedure_paid_top1_bill_cls_cd: { type: mongoose.SchemaTypes.String, required: true },
    unusual_coding_unusual_icd_procedure_paid_top2_cd: { type: mongoose.SchemaTypes.String, required: true },
    unusual_coding_unusual_icd_procedure_paid_top2_desc: { type: mongoose.SchemaTypes.String, required: true },
    unusual_coding_unusual_icd_procedure_paid_top2_amt: { type: mongoose.SchemaTypes.Decimal128, required: true },
    unusual_coding_unusual_icd_procedure_paid_top2_lob: { type: mongoose.SchemaTypes.String, required: true },
    unusual_coding_unusual_icd_procedure_paid_top2_bill_cls_cd: { type: mongoose.SchemaTypes.String, required: true },
    unusual_coding_unusual_drg_paid_pct: { type: mongoose.SchemaTypes.Decimal128, required: true },
    unusual_coding_unusual_drg_paid_peer_group_median: { type: mongoose.SchemaTypes.Decimal128, required: true },
    unusual_coding_unusual_drg_paid_percentile: { type: mongoose.SchemaTypes.Decimal128, required: true },
    unusual_coding_unusual_drg_paid_color: { type: mongoose.SchemaTypes.Number, required: true },
    unusual_coding_unusual_drg_paid_top1_cd: { type: mongoose.SchemaTypes.String, required: true },
    unusual_coding_unusual_drg_paid_top1_desc: { type: mongoose.SchemaTypes.String, required: true },
    unusual_coding_unusual_drg_paid_top1_amt: { type: mongoose.SchemaTypes.Decimal128, required: true },
    unusual_coding_unusual_drg_paid_top1_lob: { type: mongoose.SchemaTypes.String, required: true },
    unusual_coding_unusual_drg_paid_top1_bill_cls_cd: { type: mongoose.SchemaTypes.String, required: true },
    unusual_coding_unusual_drg_paid_top2_cd: { type: mongoose.SchemaTypes.String, required: true },
    unusual_coding_unusual_drg_paid_top2_desc: { type: mongoose.SchemaTypes.String, required: true },
    unusual_coding_unusual_drg_paid_top2_amt: { type: mongoose.SchemaTypes.Decimal128, required: true },
    unusual_coding_unusual_drg_paid_top2_lob: { type: mongoose.SchemaTypes.String, required: true },
    unusual_coding_unusual_drg_paid_top2_bill_cls_cd: { type: mongoose.SchemaTypes.String, required: true },
    unusual_coding_severe_drg_pct: { type: mongoose.SchemaTypes.Decimal128, required: true },
    unusual_coding_severe_drg_peer_group_median: { type: mongoose.SchemaTypes.Decimal128, required: true },
    unusual_coding_severe_drg_percentile: { type: mongoose.SchemaTypes.Decimal128, required: true },
    unusual_coding_severe_drg_color: { type: mongoose.SchemaTypes.Number, required: true },
    risk_group: { type: mongoose.SchemaTypes.String, required: true },
    total_npis_in_risk_group: { type: mongoose.SchemaTypes.Decimal128, required: true },
};

const collectionName = "facilities";
const userSchema = mongoose.Schema(schema);
const Facility = mongoose.model(collectionName, userSchema);
export default Facility;